blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://github.com/Master of Data Science at the University of British Columbia/tame_your_files/discussions
    about: Please ask and answer questions here.
